#!/bin/bash
IP=$(wget -qO- ipv4.icanhazip.com);
echo -e "--------------------------------------"
echo -e "    Script Auto Install by Potato"
echo -e "--------------------------------------"
echo -e "         Detail Konfigurasi"
echo -e "--------------------------------------"
echo -e ""
echo -e "Host         : $IP"
echo -e "Port OpenSSH : 22,444"
echo -e "Port Dropbear: 143,80,236"
echo -e "Port SSL     : 443,943"
echo -e "BadVPN UDPGW : 7100,7200,7300"
echo -e "             : 7400,7500,7600"
echo -e "Squid Proxy  : 8000,8080,8989"
echo -e "OpenVPN TCP  : 1194"
echo -e "OpenVPN SSL  : 2905,9443"
echo -e "OpenVPN UDP  : 25000"
echo -e "Config http://$IP:81/myvpn-config.zip"
echo -e ""
echo -e "--------------------------------------"
echo -e "      Donate   :   t.me/aldi_nc"
echo -e "--------------------------------------"