#!/bin/bash
#Menu Section
clear
echo -e ""
echo -e "\e[31;5m+ -- --=[  Credit by Potato  ]=-- -- +"

echo -e ""
echo -e ""
echo -e "\e[32;5m               Menu"
echo -e "==================================="
echo -e ""
echo -e "  \e[34;5mPerintah            \e[34;5mKeterangan"
echo -e "------------          ---------------"
echo -e " \e[37;5m# menu               \e[37;5mMenampilkan semua fitur perintah"
echo -e " \e[37;5m# usernew            \e[37;5mMembuat akun SSH/VPN baru"
echo -e " # perpanjang         Untuk memperpanjang akun SSH/VPN"
echo -e " # trial              \e[37;5mMembuat percobaan akun SSH/VPN"
echo -e " # delete             \e[37;5mMenghapus akun SSH/VPN"
echo -e " # cek                \e[37;5mPeriksa login user SSH/Dropbear"
echo -e " # member             \e[37;5mMenampilkan semua akun SSH/VPN"
echo -e " # userlimit 1        Untuk melimit max 1 login(not auto)"
echo -e " # userlimit 2        Untuk melimit max 2 login(not auto)"
echo -e " # limit 1            Untuk melimit max 1 login(auto)"
echo -e " # limit 2            Untuk melimit max 2 login(auto)"
echo -e " # limit stop         STOP limit 1 dan 2"
echo -e " # limit cek          Untuk melihat log user yang dilimit"
echo -e " # limit reset        Untuk mereset log/menghapus semua log"
echo -e " # onstat             \e[37;5mMengaktifkan cek user login OpenVPN"
echo -e " # offstat            \e[37;5mMenonaktifkan cek user login OpenVPN"
echo -e " # live               Live Bandwidth"
echo -e " # restart            \e[37;5mRestart SSH, OpenVPN, Squid, Dropbear"
echo -e " # reboot             \e[37;5mReboot VPS"
echo -e " # speedtest          \e[37;5mTes Kecepatan VPS"
echo -e " # cekmemory          Menampilkan sisa memory RAM"
echo -e " # cekport            Cek Port SSH/Dropbear/OpenVPN/Proxy/SSL"
echo -e " # info               \e[37;5mMenampilkan informasi sistem VPS"
echo -e " # about              \e[37;5mMenampilkan tentang Script Auto Installer"
echo -e " # exit               \e[37;5mKeluar"
echo -e ""
echo -e "\e[32;5m==========Thanks for all==========="
echo -e "\e[37;5m"

